plugins {
    id 'com.android.application'
}

configurations.all {
    resolutionStrategy {
        force 'org.jetbrains.kotlin:kotlin-stdlib:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22'
        force 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22'
    }
}

android {
    namespace 'com.hbr.streamcoredemo'
    compileSdk 34

    def streamcoreDemoApplicationId =
            providers.gradleProperty('streamcoreDemoApplicationId')
                    .orElse('com.hbr.streamcoredemo')
                    .get()

    defaultConfig {
        applicationId streamcoreDemoApplicationId
        minSdk 26
        targetSdk 34
        versionCode 10401
        versionName '1.4.1'
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),
                    'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')
    implementation files(gradle.ext.streamcoreSdkAarPath)
    implementation 'androidx.appcompat:appcompat:1.7.0'
    implementation 'androidx.core:core:1.13.1'
}
